name: Tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Node v24
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build TypeScript
        run: yarn build

      - name: Run Tests
        run: yarn test
